services:

  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: notification_app
    env_file:
      - .env
    ports:
      - "8013:8013"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./:/app

volumes:
  postgres_data:
