services:

  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  redis:
    image: redis:latest
    container_name: notification_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  celery_worker:
    build: .
    container_name: notification_celery
    command: celery -A conf worker -l info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
    volumes:
      - ./:/app

  app:
    build: .
    container_name: notification_app
    env_file:
      - .env
    ports:
      - "8013:8013"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./:/app

volumes:
  postgres_data:
  redis_data:
