services:
  postgres:
    image: postgres:15
    container_name: analytics_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      microservices_net:
        aliases:
          - analytics_db

  app:
    build: .
    container_name: analytics_app
    env_file:
      - .env
    ports:
      - "8016:8016"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: analytics_db
    volumes:
      - ./:/app
    networks:
      - microservices_net

  consumer:
    build: .
    container_name: analytics_consumer
    command: python consumer.py
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: analytics_db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./:/app
    networks:
      - microservices_net

volumes:
  postgres_data:

networks:
  microservices_net:
    name: microservices_net
    external: true
